#!/bin/bash
# v0.4.3
echo "MarkDown2Typst compiler"

# Initialize variables
file=""
template=""
out=""
bookname=""

# Function to print usage
usage() {
  echo "Usage: $0 -f=FILE | -t=TEMPLATE | -o=OUT | -b=BOOK"
  exit 1
}

# Function to convert MarkDown to Typst - esp. Obsidian-style Markdown / change as relevant
process_typst_file() {
  echo "Converting Markdown to Typst format"

  # Convert Markdown headings to Typst headings
  sed -i -e 's/^# /= /g' "$1"
  sed -i -e 's/^## /== /g' "$1"
  sed -i -e 's/^### /=== /g' "$1"
  sed -i -e 's/^#### /==== /g' "$1"
  sed -i -e 's/^##### /===== /g' "$1"
  sed -i -e 's/^###### /====== /g' "$1"

  # Remove any remaining curly brackets
  sed -i 's/{{//g; s/}}//g' "$1"

  # Convert three dashes etc. to Typst pagebreak
  # sed -i 's/(\-\-\-|\*\*\*|___)$/#pagebreak()/g' "$1"
  # Alternatively Convert horizontal rules to Typst line
  sed -i -E 's/^(\-\-\-|\*\*\*|___)$/#line\(length: 100%\)/g' "$1"

  # Convert Markdown footnotes to Typst footnotes
  sed -i 's/\[\^\(.*\)\]/#footnote[\1]/g' "$1"

  # Convert Markdown block quotes to Typst quotes - removed autoquotes to fix problem with British quotes
  sed -i -E 's/^> (.*)$/#quote(block:true, quotes:false)[\1]/g' "$1"

  # Convert Markdown italics to Typst emphasis
  sed -i -E 's/_(.*?)_/\\_\1\\_/g' "$1"
  sed -i -E 's/\*(.*?)\*/_\1_/g' "$1"

  # Convert Markdown bold to Typst strong
  sed -i -E 's/\*\*(.*?)\*\*/\*\1\*/g' "$1"
  sed -i -E 's/__(.*?)__/\\*\1\\*/g' "$1"

  # Convert HTML underline to Typst underline
  sed -i -E 's/<u>(.*?)<\/u>/#underline[\1]/g' "$1"

  # Convert Markdown comments to Typst comments
  sed -i -E 's/%%(.*?)%%/\/\*\1\*\//g' "$1"

  # Convert strikethrough text to Typst strike
#  sed -i -E 's/~~(.*?)~~/#strike[\1]/g' "$1"

  # Convert highlighted text to Typst highlight
  sed -i -E 's/==(.*?)==/#highlight[\1]/g' "$1"

  # Convert + bullets to - bullets
  sed -i -E 's/^\+ /- /g' "$1"

  # Convert Markdown links to Typst links
  sed -i -E 's/\[(.*?)\]\((.*?)\)/#link("\2")[\1]/g' "$1"

  # Remove Markdown front matter - can mistake for HR page break
  # sed -i -e '/^---$/,/^---$/d' "$1"

  # Remove everything between ```dataview and the next ``` - enable if needed
  # sed -i '/^```dataview$/,/^```$/d' "$1"

  # Convert Markdown photos to Typst photos - presumes images are in the same directory
  # sed -i 's/!\[\[\(.*\)\]\]/image("\1")/g' "$1"

  typst compile "$book_path/$bookname.typ"
}

# Parse command-line arguments
for arg in "$@"; do
  case $arg in
  -f=* | --file=*)
    file="${arg#*=}"
    shift
    ;;
  -t=* | --template=*)
    template="${arg#*=}"
    shift
    ;;
  -o=* | --out=*)
    out="${arg#*=}"
    shift
    ;;
  -b=* | --book=*)
    bookname="${arg#*=}"
    shift
    ;;
  *)
    echo "Invalid argument: $arg"
    usage
    ;;
  esac
done

# Check if -f or -b is provided
if [ -z "$file" ] && [ -z "$bookname" ]; then
  echo "Error: Please supply a file or bookname"
  usage
fi

# If -f is specified, run the compiler
if [ -n "$file" ]; then
  if [ -n "$out" ]; then
    typst compile "$file.typ" "$out"
    echo "Outputted $out"
  else
    echo "Error: Please specify the output file using -o"
    usage
  fi
  exit 0
fi

# Function to read a value from a TOML file
get_toml_value() {
  local file=$1
  local key=$2
  # Extract the value using grep and sed
  local value=$(grep -oP "^$key\s*=\s*\"?\K[^\"]+" "$file")
  echo "$value" # needs this to output converted Typst
}

read_toml_value() {
  echo "Reading $src_path/book.toml values"
  local tomlpath="$src_path/book.toml"

  # Read values from the book.toml file
  title=$(get_toml_value "$tomlpath" "title")
  sub_title=$(get_toml_value "$tomlpath" "sub-title")
  authors=$(get_toml_value "$tomlpath" "authors")
  description=$(get_toml_value "$tomlpath" "description")
  copyright_year=$(get_toml_value "$tomlpath" "copyright-year")
  this_edition=$(get_toml_value "$tomlpath" "this-edition")
  published_by=$(get_toml_value "$tomlpath" "published-by")
  printed_by=$(get_toml_value "$tomlpath" "printed-by")
  contact_address=$(get_toml_value "$tomlpath" "contact-address")
  #website_address=$(get_toml_value "$tomlpath" "website-address")
  dedication=$(get_toml_value "$tomlpath" "dedication")
  page_size=$(get_toml_value "$tomlpath" "page-size")
  outer_margin=$(get_toml_value "$tomlpath" "outer-margin")
  inner_margin=$(get_toml_value "$tomlpath" "inner-margin")
  header=$(get_toml_value "$tomlpath" "header")
  footer=$(get_toml_value "$tomlpath" "footer")
  contents=$(get_toml_value "$tomlpath" "contents")
  fiction=$(get_toml_value "$tomlpath" "fiction")
  cover_image=$(get_toml_value "$tomlpath" "cover-image")
}

replace_template_values() {
  local template_file="$book_path/TEMPLATE.typ"
  # Replace placeholders in TEMPLATE.typ
  echo "Replacing template values in $template_file"
  sed -i "s/{{\$title}}/$title/g" "$template_file"
  sed -i "s/{{\$sub-title}}/$sub_title/g" "$template_file"
  sed -i "s/{{\$authors}}/$authors/g" "$template_file"
  sed -i "s/{{\$description}}/$description/g" "$template_file"
  sed -i "s/{{\$copyright-year}}/$copyright_year/g" "$template_file"
  sed -i "s/{{\$this-edition}}/$this_edition/g" "$template_file"
  sed -i "s/{{\$published-by}}/$published_by/g" "$template_file"
  sed -i "s/{{\$printed-by}}/$printed_by/g" "$template_file"
  sed -i "s/{{\$contact-address}}/$contact_address/g" "$template_file"
  sed -i "s/{{\$website-address}}/$website_address/g" "$template_file"
  sed -i "s/{{\$dedication}}/$dedication/g" "$template_file"
  sed -i "s/{{\$page-size}}/$page_size/g" "$template_file"
  sed -i "s/{{\$outer-margin}}/$outer_margin/g" "$template_file"
  sed -i "s/{{\$inner-margin}}/$inner_margin/g" "$template_file"
  sed -i "s/{{\$header}}/$header/g" "$template_file"
  sed -i "s/{{\$footer}}/$footer/g" "$template_file"
  # sed -i "s/{{\$contents}}/$contents/g" "$template_file"
  sed -i "s/{{\$cover-image}}/$cover_image/g" "$template_file"
}

# If -b is specified, set the bookname
if [ -n "$bookname" ]; then

  # ADD check the directory exists

  book_path="$bookname/book"
  src_path="$bookname/src"
  typ_file="$book_path/$bookname.typ"
  md_file="$book_path/$bookname.md"
  pdf_file="$book_path/$bookname.pdf"

  # Copy the Markdown content to the Typst file
  cp "$md_file" "$typ_file"

  # Process the Typst file
  process_typst_file "$typ_file"

#  echo "$src_path/TEMPLATE.typ found?"

  # Check if there is a TEMPLATE.typ file in $bookName/src
  if [ -f "$src_path/TEMPLATE.typ" ]; then
    # Copy the TEMPLATE.typ file to the $bookName/book folder
    # echo "Found $src_path/TEMPLATE.typ"
    cp "$src_path/TEMPLATE.typ" "$book_path/TEMPLATE.typ"
  fi

  # Check if there is a book.toml file in $bookName/src
  if [ -f "$src_path/book.toml" ]; then
    # Call the procedure to copy the values from book.toml to TEMPLATE.typ
    # echo "add book.toml populating TEMPLATE.typ here"
    read_toml_value
    replace_template_values
  fi

  # Add the template to the start of the Typst file (if specified)
  if [ -n "$template" ]; then # if no template specified
    cat "$template" "$typ_file" >"$typ_file.tmp" && mv "$typ_file.tmp" "$typ_file"
  else # if template in book directory
    if [ -f "$book_path/TEMPLATE.typ" ]; then
#      echo "Found $book_path/TEMPLATE.typ"
      cat "$book_path/TEMPLATE.typ" "$typ_file" >"$typ_file.tmp" && mv "$typ_file.tmp" "$typ_file"
    fi
  fi

  # Run the typst compiler
  typst compile "$typ_file" "$pdf_file"
  echo "Outputted $pdf_file"
  exit 0
fi

# If no valid action was taken, show usage
usage
