[book]
title = "Book Test"
authors = ["John Doe"]
description = "The example book covers examples."
copyright-year = "2024"
this-edition = "1st"
printed-by = "ACME printing"
contact-address = ""
website-address = ""

[output]
page-size = a5
outer-margin = 0.50in
inner-margin = 0.90in
header = "" # not yet implemented
footer = "" # notyet implemented
contents = TRUE # not yet implemented
