# v0.5.0
[book]
title = "Book Test"
sub-title = "Sub Title"
authors = "John Doe"
description = "The example book covers examples."
copyright-year = "2024"
this-edition = "1st"
published-by = "Publisher"
printed-by = "ACME printing"
contact-address = "1 Address"
website-address = "http://address"
dedication = "dedication"
disclaimer = "disclaimer"

[output]
page-size = a5
outer-margin = 0.50in
inner-margin = 0.90in
header = "" # not yet implemented
footer = "" # not yet implemented
contents = "TRUE" # not yet implemented
fiction = "TRUE" # not yet implemented
